### ISSUE TITLE
Shutdown-on-LAN

### ISSUE THREAD

**Issue by AtmanActive** [SR-G/sleep-on-lan#1]
Hello Serge,

Thank you very much for this great software.

Would it be too much to ask to also add shutdown functionality?
Preferably via config option.

Here is my usage scenario:
I have built a Steam machine based on windows for my kids to play Lego games.
It is connected to Samsung Smart TV which is also connected with ethernet to my home network.
In my home network I use MikroTik as my home router and this router is pretty advanced, it can even do scripting, so with two lines of code I have instructed it to ping my TV's IP and when it detects that it is down (TV off) to send magic packet to MAC address A, and when it detects that the state changed from down to up (TV on) to send magic packet to MAC address B. 
Now, this motherboard (Gigabyte GA-Z97N-WIFI) and Intel ethernet chip support wake-on-lan even from shutdown state, which is awesome.
And I would always prefer for the machine to go to shutdown and boot back on when needed, then to go sleep-wake-sleep-wake. Still to this day, for millions of unknown reasons, windows machine runs smoothly only after a fresh boot, while after a week of running dozens of steam games (without any sleep or shutdown) something always goes wrong and the machine runs jerky and slowed down.
So, the only piece I am missing right now is Shutdown-on-LAN.
Using windows' built-in idle timers is impossible as kids will always leave a full screen game on pause and that will prevent any idle detection.

Let me know what do you think about this.

Thanks.

Cheers!

**Comment by SR-G** [comment]
Hey.

I see.
At first i was using a (configurable) command but it wasn't working well on windows so i switched on windows to a DLL API call instead (but it's still configurable for linux).
I'll see how i can restore the possibility to configure the executed command on windows (that way you should then be able to use a "shutdown" command instead of a "sleep" one).

**Comment by AtmanActive** [comment]
Thanks.

Issuing a windows DLL API call to perform a shutdown is also OK.

Sure, I could fork the project and just change the line 15 in sleep-on-lan/src/main/go/sol/sleeper_windows.go, but then we would have two separate projects, one for sleep and the other for shutdown, where it would be best if it could be a single program and just a config line 'shutdown=1' that would do shutdown instead of sleep.
In that way, the user can experiment and try both approaches.

I think I could do it, if you wish, but then I would just kindly ask you to instruct me about how to compile it.

**Comment by SR-G** [comment]
Yep. 

I'm about to commit a modification that won't change anything by default, but that will allow to customize the command executed (and also to register new additionnal commands if needed).

In your case you'll have to configure the sol.json configuration file with something like : 
> {
>   "Listeners" : ["UDP:9", "UDP:7", "HTTP:8009" ],
>   "LogLevel" : "INFO",
>   "Commands" : [ 
> 	{
> 		"Operation" : "halt",
> 		"Command" : "C:\\Windows\\System32\\Shutdown.exe -s -t 0"
> 	}
>   ]
> }

With only one command defined, that command will be used by default (and thus will react to magic packets).
This operation will also be published (if an HTTP listener is defined) on the http://<IP>:<PORT>/halt URL if you want / need to call it from a remote system through http (with curl or wget or anything else).

I'm not willing to have in the configuration "shutdown = 1" or something like that, because if someone needs someday an "hibernate-on-sleep" or anything else, it would then be necessary to deal with all behaviors in code (for all platforms).  The "sleep-on-lan behavior" by default + the possibility to customize anything else if needed, as generic commands, seems less restrictive.

**Comment by AtmanActive** [comment]
Hi Serge,

Thank you very much for your quick upgrades.

Unfortunately, I can't make it work.

Continued here:
https://github.com/SR-G/sleep-on-lan/issues/2
https://github.com/SR-G/sleep-on-lan/issues/3
