### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by lkd70** [SR-G/sleep-on-lan#12]
It'd seem tensin-app-golang isn't available, do we need your stack, too?

`Unable to find image 'tensin-app-golang:latest' locally`

![image](https://user-images.githubusercontent.com/7032715/32922835-2a7d7ad4-cb2c-11e7-98e2-db8c389d021f.png)

**Comment by SR-G** [comment]
Right, not generic for the now as this has been quickly put in place yesterday in order to automate the build process. I'll see how to make something cleaner. My docker golang image has just a few enhancements (a few dependencies like zip, a few aliases). You can still compile without docker if needed for a PR, or with the regular library/golang docker image (but not with the makefile for the now).

**Comment by lkd70** [comment]
Thats fine, as long as it's not intended to work for us then all is good 👍 
I'll hold off until there's a 'generic' build method, that way I can blame you if stuff doesn't work 👅

**Comment by SR-G** [comment]
Partly resolved now with an evolution of the Makefile (allowing to use a standard library/golang docker image) - be aware that for distribution, you still need additional packages (like zip and make), so have to install that in the image.
